import "dotenv-flow/config";
import fs from "node:fs/promises";
import path from "node:path";
import { closeDb } from "@heiso/core/lib/db";
import { db } from "@heiso/core/lib/db";
import { settings } from "@heiso/core/lib/db/schema";
import { eq } from "drizzle-orm";

type MenuModule = {
  name: string;
  path: string;
  icon: string;
  group: string;
  sortOrder: number;
};

async function getModulesFromSettings(): Promise<MenuModule[]> {
  const row = await db.query.settings.findFirst({
    where: eq(settings.name, "modules"),
  });

  if (!row) {
    throw new Error(
      "Settings row 'modules' not found. Run 'hive apps sync' to populate tenant DB settings."
    );
  }

  const value = row.value as unknown;
  if (!Array.isArray(value)) {
    throw new Error(
      `Settings 'modules' value is not an array: ${JSON.stringify(value)}`
    );
  }

  return value as MenuModule[];
}

function buildMenusConfigContent(list: MenuModule[]): string {
  const header = `// This file is auto-generated by scripts/fetchMenuFromDb.ts\n// Do not edit this file manually.\n`;

  const typeDef = `export type GeneratedMenu = {
  readonly name: string;
  readonly path: string;
  readonly icon: string;
  readonly group: string;
  readonly sortOrder: number;
};\n`;

  const sorted = [...list].sort((a, b) => a.sortOrder - b.sortOrder);
  const arrayLiteral = JSON.stringify(sorted, null, 2);
  const body = `export const generatedMenus = ${arrayLiteral} as const satisfies readonly GeneratedMenu[];\n`;

  return `${header}\n${typeDef}\n${body}`;
}

async function writeMenusToConfig() {
  try {
    const modules = await getModulesFromSettings();
    const content = buildMenusConfigContent(modules);
    const targetPath = path.resolve(
      process.cwd(),
      "config",
      "generated",
      "menus.ts"
    );
    await fs.writeFile(targetPath, content, "utf8");
    console.log(`Menu config written to: ${targetPath}`);
  } catch (err) {
    console.error("Failed to write menu config:", err);
    process.exitCode = 1;
  } finally {
    try {
      await closeDb();
    } catch (_e) {
      // ignore close errors
    }
  }
}

writeMenusToConfig();
