import "dotenv-flow/config";
import fs from "node:fs/promises";
import path from "node:path";
import { closeDb } from "@heiso/core/lib/db";
import { getDynamicDb } from "@heiso/core/lib/db/dynamic";

async function getAllPermissions() {
  const db = await getDynamicDb();
  const permissions = await db.query.permissions.findMany({
    columns: {
      id: true,
      resource: true,
      action: true,
    },
    with: {
      menus: {
        columns: {
          id: true,
          title: true,
          path: true,
        },
      },
    },
    where: (t, ops) => ops.isNull(t.deletedAt),
  });

  // console.log('permissions: ', permissions);

  return permissions;
}

export type PermissionItem = {
  id: string;
  resource: string;
  action: string;
  menu: {
    id: string;
    title: string;
    path?: string | null;
  };
};

function buildPermissionsConfigContent(list: PermissionItem[]): string {
  const header = `// This file is auto-generated by scripts/fetchPermissionFromDb.ts\n// Do not edit this file manually.\n`;

  const typeDef = `export type PermissionConfigShape = {\n  readonly id: string;\n  readonly resource: string;\n  readonly action: string;\n  readonly menu: { readonly id: string; readonly title: string; readonly path?: string | null } | null;\n};\n`;

  const arrayLiteral = JSON.stringify(list, null, 2);
  const body = `export const permissionsConfig = ${arrayLiteral} as const satisfies readonly PermissionConfigShape[];\n\nexport type PermissionResource = (typeof permissionsConfig)[number]['resource'];\nexport type PermissionAction = (typeof permissionsConfig)[number]['action'];\n`;

  return `${header}\n${typeDef}\n${body}`;
}

async function writePermissionsToConfig() {
  try {
    const permissions = await getAllPermissions();
    const list: PermissionItem[] = permissions
      .filter((p) => p.menus)
      .map((p) => ({
        id: p.id,
        resource: p.resource,
        action: p.action,
        menu: p.menus!,
      }));

    const content = buildPermissionsConfigContent(list);
    const targetPath = path.resolve(process.cwd(), "config", "permissions.ts");
    await fs.writeFile(targetPath, content, "utf8");
    console.log(`Permissions config written to: ${targetPath}`);
  } catch (err) {
    console.error("Failed to write permissions config:", err);
    process.exitCode = 1;
  } finally {
    // Always close DB connections so the process can exit cleanly
    try {
      await closeDb();
    } catch (_e) {
      // ignore close errors
    }
  }
}

writePermissionsToConfig();
