// This file is auto-generated by scripts/fetchPermissionFromDb.ts
// Do not edit this file manually.

export type PermissionConfigShape = {
  readonly id: string;
  readonly resource: string;
  readonly action: string;
  readonly menu: { readonly id: string; readonly title: string; readonly path?: string | null } | null;
};

export const permissionsConfig = [] as const satisfies readonly PermissionConfigShape[];

export type PermissionResource = (typeof permissionsConfig)[number]['resource'];
export type PermissionAction = (typeof permissionsConfig)[number]['action'];
